name: slick-extra
version: '0.1.0.0'
category: Web
author: Sergey Bushnyak
maintainer: sergey.bushnyak@sigrlami.eu
copyright: ! ' Copyright: (c) 2019 Migamake Pte Ltd
             , Sergey Bushnyak'
license: BSD3
github: sigrlami/slick-extra
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5
- slick
- text
- shake
- pandoc
- aeson
- lens-aeson
- lens
- extra
- directory
library:
  source-dirs: src
  exposed-modules:
  - Slick.Extra
